package modelo;

import java.sql.Date;

public class Persona {
	private String PER_PRIMER_NOMBRE;
	private int PER_TELEFONO;
	private String PER_SEGUNDO_NOMBRE;
	private String PER_PRIMER_APELLIDO;
	private String PER_SEGUNDO_APELLIDO;
	private int PER_NUMEROIDENTIFICACION;
	private int MUN_CODIGO;
	private int MUN_MUN_CODIGO;
	private int EDB_CODIGO;
	private String PER_TIPO_IDENTIFICACION;
	private String PER_SEXO;
	private int PER_N_LIBRETA_MILITAR;
	private String PER_CLASE_LM;
	private String PER_DM_LIBRETA;
	private String PER_DIRECCION_CORRESPONDENCIA;
	private Date PER_FECHA_NACIMIENTO;
	private String PER_MAIL;
	
	public Persona(String pER_PRIMER_NOMBRE, int pER_TELEFONO, String pER_SEGUNDO_NOMBRE, String pER_PRIMER_APELLIDO,
			String pER_SEGUNDO_APELLIDO, int pER_NUMEROIDENTIFICACION, int mUN_CODIGO, int mUN_MUN_CODIGO,
			int eDB_CODIGO, String pER_TIPO_IDENTIFICACION, String pER_SEXO, int pER_N_LIBRETA_MILITAR,
			String pER_CLASE_LM, String pER_DM_LIBRETA, String pER_DIRECCION_CORRESPONDENCIA, Date pER_FECHA_NACIMIENTO,
			String pER_MAIL) {
		super();
		PER_PRIMER_NOMBRE = pER_PRIMER_NOMBRE;
		PER_TELEFONO = pER_TELEFONO;
		PER_SEGUNDO_NOMBRE = pER_SEGUNDO_NOMBRE;
		PER_PRIMER_APELLIDO = pER_PRIMER_APELLIDO;
		PER_SEGUNDO_APELLIDO = pER_SEGUNDO_APELLIDO;
		PER_NUMEROIDENTIFICACION = pER_NUMEROIDENTIFICACION;
		MUN_CODIGO = mUN_CODIGO;
		MUN_MUN_CODIGO = mUN_MUN_CODIGO;
		EDB_CODIGO = eDB_CODIGO;
		PER_TIPO_IDENTIFICACION = pER_TIPO_IDENTIFICACION;
		PER_SEXO = pER_SEXO;
		PER_N_LIBRETA_MILITAR = pER_N_LIBRETA_MILITAR;
		PER_CLASE_LM = pER_CLASE_LM;
		PER_DM_LIBRETA = pER_DM_LIBRETA;
		PER_DIRECCION_CORRESPONDENCIA = pER_DIRECCION_CORRESPONDENCIA;
		PER_FECHA_NACIMIENTO = pER_FECHA_NACIMIENTO;
		PER_MAIL = pER_MAIL;
	}

	public String getPER_PRIMER_NOMBRE() {
		return PER_PRIMER_NOMBRE;
	}

	public int getPER_TELEFONO() {
		return PER_TELEFONO;
	}

	public String getPER_SEGUNDO_NOMBRE() {
		return PER_SEGUNDO_NOMBRE;
	}

	public String getPER_PRIMER_APELLIDO() {
		return PER_PRIMER_APELLIDO;
	}

	public String getPER_SEGUNDO_APELLIDO() {
		return PER_SEGUNDO_APELLIDO;
	}

	public int getPER_NUMEROIDENTIFICACION() {
		return PER_NUMEROIDENTIFICACION;
	}

	public int getMUN_CODIGO() {
		return MUN_CODIGO;
	}

	public int getMUN_MUN_CODIGO() {
		return MUN_MUN_CODIGO;
	}

	public int getEDB_CODIGO() {
		return EDB_CODIGO;
	}

	public String getPER_TIPO_IDENTIFICACION() {
		return PER_TIPO_IDENTIFICACION;
	}

	public String getPER_SEXO() {
		return PER_SEXO;
	}

	public int getPER_N_LIBRETA_MILITAR() {
		return PER_N_LIBRETA_MILITAR;
	}

	public String getPER_CLASE_LM() {
		return PER_CLASE_LM;
	}

	public String getPER_DM_LIBRETA() {
		return PER_DM_LIBRETA;
	}

	public String getPER_DIRECCION_CORRESPONDENCIA() {
		return PER_DIRECCION_CORRESPONDENCIA;
	}

	public Date getPER_FECHA_NACIMIENTO() {
		return PER_FECHA_NACIMIENTO;
	}

	public String getPER_MAIL() {
		return PER_MAIL;
	}

	public void setPER_PRIMER_NOMBRE(String pER_PRIMER_NOMBRE) {
		PER_PRIMER_NOMBRE = pER_PRIMER_NOMBRE;
	}

	public void setPER_TELEFONO(int pER_TELEFONO) {
		PER_TELEFONO = pER_TELEFONO;
	}

	public void setPER_SEGUNDO_NOMBRE(String pER_SEGUNDO_NOMBRE) {
		PER_SEGUNDO_NOMBRE = pER_SEGUNDO_NOMBRE;
	}

	public void setPER_PRIMER_APELLIDO(String pER_PRIMER_APELLIDO) {
		PER_PRIMER_APELLIDO = pER_PRIMER_APELLIDO;
	}

	public void setPER_SEGUNDO_APELLIDO(String pER_SEGUNDO_APELLIDO) {
		PER_SEGUNDO_APELLIDO = pER_SEGUNDO_APELLIDO;
	}

	public void setPER_NUMEROIDENTIFICACION(int pER_NUMEROIDENTIFICACION) {
		PER_NUMEROIDENTIFICACION = pER_NUMEROIDENTIFICACION;
	}

	public void setMUN_CODIGO(int mUN_CODIGO) {
		MUN_CODIGO = mUN_CODIGO;
	}

	public void setMUN_MUN_CODIGO(int mUN_MUN_CODIGO) {
		MUN_MUN_CODIGO = mUN_MUN_CODIGO;
	}

	public void setEDB_CODIGO(int eDB_CODIGO) {
		EDB_CODIGO = eDB_CODIGO;
	}

	public void setPER_TIPO_IDENTIFICACION(String pER_TIPO_IDENTIFICACION) {
		PER_TIPO_IDENTIFICACION = pER_TIPO_IDENTIFICACION;
	}

	public void setPER_SEXO(String pER_SEXO) {
		PER_SEXO = pER_SEXO;
	}

	public void setPER_N_LIBRETA_MILITAR(int pER_N_LIBRETA_MILITAR) {
		PER_N_LIBRETA_MILITAR = pER_N_LIBRETA_MILITAR;
	}

	public void setPER_CLASE_LM(String pER_CLASE_LM) {
		PER_CLASE_LM = pER_CLASE_LM;
	}

	public void setPER_DM_LIBRETA(String pER_DM_LIBRETA) {
		PER_DM_LIBRETA = pER_DM_LIBRETA;
	}

	public void setPER_DIRECCION_CORRESPONDENCIA(String pER_DIRECCION_CORRESPONDENCIA) {
		PER_DIRECCION_CORRESPONDENCIA = pER_DIRECCION_CORRESPONDENCIA;
	}

	public void setPER_FECHA_NACIMIENTO(Date pER_FECHA_NACIMIENTO) {
		PER_FECHA_NACIMIENTO = pER_FECHA_NACIMIENTO;
	}

	public void setPER_MAIL(String pER_MAIL) {
		PER_MAIL = pER_MAIL;
	}
	
}
