package modelo;

public class Programa {
	private int PRO_CODIGO_SNIES;
	private int UNI_CODIGO_IES;
	private String PRO_MODALIDADEDUCATIVA;
	private String PRO_TITULO;
	private int PRO_NO_SEMESTRES_APROBADO;
	
	public Programa(int pRO_CODIGO_SNIES, int uNI_CODIGO_IES, String pRO_MODALIDADEDUCATIVA, String pRO_TITULO,
			int pRO_NO_SEMESTRES_APROBADO) {
		super();
		PRO_CODIGO_SNIES = pRO_CODIGO_SNIES;
		UNI_CODIGO_IES = uNI_CODIGO_IES;
		PRO_MODALIDADEDUCATIVA = pRO_MODALIDADEDUCATIVA;
		PRO_TITULO = pRO_TITULO;
		PRO_NO_SEMESTRES_APROBADO = pRO_NO_SEMESTRES_APROBADO;
	}

	public int getPRO_CODIGO_SNIES() {
		return PRO_CODIGO_SNIES;
	}

	public int getUNI_CODIGO_IES() {
		return UNI_CODIGO_IES;
	}

	public String getPRO_MODALIDADEDUCATIVA() {
		return PRO_MODALIDADEDUCATIVA;
	}

	public String getPRO_TITULO() {
		return PRO_TITULO;
	}

	public int getPRO_NO_SEMESTRES_APROBADO() {
		return PRO_NO_SEMESTRES_APROBADO;
	}

	public void setPRO_CODIGO_SNIES(int pRO_CODIGO_SNIES) {
		PRO_CODIGO_SNIES = pRO_CODIGO_SNIES;
	}

	public void setUNI_CODIGO_IES(int uNI_CODIGO_IES) {
		UNI_CODIGO_IES = uNI_CODIGO_IES;
	}

	public void setPRO_MODALIDADEDUCATIVA(String pRO_MODALIDADEDUCATIVA) {
		PRO_MODALIDADEDUCATIVA = pRO_MODALIDADEDUCATIVA;
	}

	public void setPRO_TITULO(String pRO_TITULO) {
		PRO_TITULO = pRO_TITULO;
	}

	public void setPRO_NO_SEMESTRES_APROBADO(int pRO_NO_SEMESTRES_APROBADO) {
		PRO_NO_SEMESTRES_APROBADO = pRO_NO_SEMESTRES_APROBADO;
	}
	
}
